### ISSUE TITLE
Deprecation warning on recent ember versions

### ISSUE THREAD

**Issue by krukid** [BBVAEngineering/ember-cli-workbox#99]
Just bumped my package versions and received the following deprecation on build:

> DEPRECATION: Ember CLI addons manage their own module transpilation during the `treeForAddon` processing. `ember-cli-workbox` (found at `/proj_dir/node_modules/ember-cli-workbox`) has overridden the `this.options.ember-cli-babel` options which conflicts with the addons ability to transpile its `addon/` files properly. Falling back to default babel configuration options.

Possibly related to https://github.com/babel/ember-cli-babel/issues/136

Versions:
ember-source 3.19
ember-cli 3.19
ember-cli-babel 7.21.0
@babel/core 7.10.4

**Comment by adrigzr** [comment]
Fixed in v2.0.0.
